const students = [
  {
    fullName: "Alice Smith",
    age: 17,
    dateOfBirth: "2006-03-20",
    class: "10th",
    subjects: {
      math: { marks: 90 },
      computer_science: { marks: 88 },
      physics: { marks: 78 },
      chemistry: { marks: 92 },
      language: { marks: 85 },
    },
    percentage: 86.6,
    grade: "A",
  },
  {
    fullName: "Bob Johnson",
    age: 18,
    dateOfBirth: "2005-08-10",
    class: "12th",
    subjects: {
      math: { marks: 85 },
      computer_science: { marks: 80 },
      physics: { marks: 92 },
      chemistry: { marks: 88 },
      language: { marks: 75 },
    },
    percentage: 82.0,
    grade: "B",
  },
  {
    fullName: "Emily Davis",
    age: 17,
    dateOfBirth: "2006-01-25",
    class: "10th",
    subjects: {
      math: { marks: 92 },
      computer_science: { marks: 78 },
      physics: { marks: 85 },
      chemistry: { marks: 90 },
      language: { marks: 88 },
    },
    percentage: 86.6,
    grade: "A",
  },
  {
    fullName: "David Brown",
    age: 18,
    dateOfBirth: "2005-11-05",
    class: "12th",
    subjects: {
      math: { marks: 88 },
      computer_science: { marks: 92 },
      physics: { marks: 75 },
      chemistry: { marks: 80 },
      language: { marks: 85 },
    },
    percentage: 82.0,
    grade: "B",
  },
  {
    fullName: "Sophia Wilson",
    age: 17,
    dateOfBirth: "2006-06-15",
    class: "11th",
    subjects: {
      math: { marks: 78 },
      computer_science: { marks: 85 },
      physics: { marks: 90 },
      chemistry: { marks: 92 },
      language: { marks: 88 },
    },
    percentage: 86.6,
    grade: "A",
  },
  {
    fullName: "Michael Lee",
    age: 18,
    dateOfBirth: "2005-04-30",
    class: "12th",
    subjects: {
      math: { marks: 92 },
      computer_science: { marks: 88 },
      physics: { marks: 85 },
      chemistry: { marks: 78 },
      language: { marks: 90 },
    },
    percentage: 86.6,
    grade: "A",
  },
  {
    fullName: "Olivia Taylor",
    age: 17,
    dateOfBirth: "2006-09-10",
    class: "11th",
    subjects: {
      math: { marks: 90 },
      computer_science: { marks: 78 },
      physics: { marks: 85 },
      chemistry: { marks: 92 },
      language: { marks: 88 },
    },
    percentage: 86.6,
    grade: "A",
  },
  {
    fullName: "Daniel Martinez",
    age: 18,
    dateOfBirth: "2005-12-20",
    class: "12th",
    subjects: {
      math: { marks: 85 },
      computer_science: { marks: 88 },
      physics: { marks: 92 },
      chemistry: { marks: 78 },
      language: { marks: 90 },
    },
    percentage: 86.6,
    grade: "A",
  },
  {
    fullName: "Ava Anderson",
    age: 17,
    dateOfBirth: "2006-05-05",
    class: "11th",
    subjects: {
      math: { marks: 88 },
      computer_science: { marks: 90 },
      physics: { marks: 85 },
      chemistry: { marks: 78 },
      language: { marks: 92 },
    },
    percentage: 86.6,
    grade: "A",
  },
  {
    fullName: "William Thomas",
    age: 18,
    dateOfBirth: "2005-10-15",
    class: "10th",
    subjects: {
      math: { marks: 92 },
      computer_science: { marks: 85 },
      physics: { marks: 88 },
      chemistry: { marks: 78 },
      language: { marks: 90 },
    },
    percentage: 86.6,
    grade: "A",
  },
];
module.exports = { students };
