const students = [
  {
    id: 1,
    fullName: "Alice Smith",
    age: 17,
    dateOfBirth: "2006-03-20",
    class: "10th",
    subjects: {
      math: { marks: 90 },
      computer_science: { marks: 92 },
      physics: { marks: 93 },
      chemistry: { marks: 93 },
      language: { marks: 87 },
    },
    percentage: 91,
    grade: "A+",
  },
  {
    id: 2,
    fullName: "Bob Johnson",
    age: 18,
    dateOfBirth: "2005-08-10",
    class: "12th",
    subjects: {
      math: { marks: 85 },
      computer_science: { marks: 80 },
      physics: { marks: 92 },
      chemistry: { marks: 88 },
      language: { marks: 75 },
    },
    percentage: 82.0,
    grade: "B",
  },
  {
    id: 3,
    fullName: "Emily Davis",
    age: 17,
    dateOfBirth: "2006-01-25",
    class: "10th",
    subjects: {
      math: { marks: 92 },
      computer_science: { marks: 78 },
      physics: { marks: 85 },
      chemistry: { marks: 90 },
      language: { marks: 88 },
    },
    percentage: 86.6,
    grade: "A",
  },
  {
    id: 4,
    fullName: "David Brown",
    age: 18,
    dateOfBirth: "2005-11-05",
    class: "12th",
    subjects: {
      math: { marks: 88 },
      computer_science: { marks: 92 },
      physics: { marks: 75 },
      chemistry: { marks: 80 },
      language: { marks: 85 },
    },
    percentage: 82.0,
    grade: "B",
  },
  {
    id: 5,
    fullName: "Sophia Wilson",
    age: 17,
    dateOfBirth: "2006-06-15",
    class: "11th",
    subjects: {
      math: { marks: 55 },
      computer_science: { marks: 64 },
      physics: { marks: 40 },
      chemistry: { marks: 23 },
      language: { marks: 62 },
    },
    percentage: 48.8,
    grade: "F",
  },
  {
    id: 6,
    fullName: "Michael Lee",
    age: 18,
    dateOfBirth: "2005-04-30",
    class: "12th",
    subjects: {
      math: { marks: 92 },
      computer_science: { marks: 88 },
      physics: { marks: 85 },
      chemistry: { marks: 78 },
      language: { marks: 90 },
    },
    percentage: 86.6,
    grade: "A",
  },
  {
    id: 7,
    fullName: "Olivia Taylor",
    age: 17,
    dateOfBirth: "2006-09-10",
    class: "11th",
    subjects: {
      math: { marks: 90 },
      computer_science: { marks: 78 },
      physics: { marks: 85 },
      chemistry: { marks: 92 },
      language: { marks: 88 },
    },
    percentage: 86.6,
    grade: "A",
  },
  {
    id: 8,
    fullName: "Daniel Martinez",
    age: 18,
    dateOfBirth: "2005-12-20",
    class: "12th",
    subjects: {
      math: { marks: 85 },
      computer_science: { marks: 88 },
      physics: { marks: 92 },
      chemistry: { marks: 78 },
      language: { marks: 90 },
    },
    percentage: 86.6,
    grade: "A",
  },
  {
    id: 9,
    fullName: "Ava Anderson",
    age: 17,
    dateOfBirth: "2006-05-05",
    class: "11th",
    subjects: {
      math: { marks: 88 },
      computer_science: { marks: 90 },
      physics: { marks: 85 },
      chemistry: { marks: 78 },
      language: { marks: 92 },
    },
    percentage: 86.6,
    grade: "A",
  },
  {
    id: 10,
    fullName: "William Thomas",
    age: 18,
    dateOfBirth: "2005-10-15",
    class: "10th",
    subjects: {
      math: { marks: 50 },
      computer_science: { marks: 60 },
      physics: { marks: 80 },
      chemistry: { marks: 70 },
      language: { marks: 90 },
    },
    percentage: 70,
    grade: "C",
  },
];
module.exports = { students };
